print("Hello World")
print("This is a Git Tutorial V1 before deletion")
print("I am making some changes to the V1 configuration")
print("This is an updated version of Version 1")
print("This is Version 1 being updated to Version 4")
print("I am making some changes but adding to the same commit")